application: section-14
version: v1
api_version: 1
runtime: python27
threadsafe: yes

handlers:
- url: /bower_components
  static_dir: bower_components
- url: /general
  static_dir: general
- url: /projects
  static_dir: projects
- url: /js
  static_dir: js
- url: /styles
  static_dir: styles
- url: /elements
  static_dir: elements
- url: /images
  static_dir: images
- url: /pdf
  static_dir: pdf
- url: /elements.html
  static_files: elements.html
  upload: elements.html
- url: /imports.html
  static_files: imports.html
  upload: imports.html
- url: /
  static_files: index.html
  upload: index.html
